// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptmhrfovbyvpewfdpejf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0bWhyZm92Ynl2cGV3ZmRwZWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxNjkyNzAsImV4cCI6MjA4OTc0NTI3MH0.0q-1UB9WZhmFCOXudEJ6lCUYW1ZTzC6yRUkftD6tC1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
  }
});